package gregtechmod.loaders.postload;

import gregtechmod.GT_Mod;
import gregtechmod.api.util.GT_Log;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

public class GT_SonictronLoader implements Runnable {
	@Override
	public void run() {
		GT_Log.out.println("GT_Mod: Loading Sonictron Sounds");
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.blockIron, 1));
    	GT_Mod.mSoundNames.add("note.harp");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.blockGold, 1));
    	GT_Mod.mSoundNames.add("note.pling");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.stone, 1));
    	GT_Mod.mSoundNames.add("note.bd");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.log, 1));
    	GT_Mod.mSoundNames.add("note.bassattack");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.planks, 1));
    	GT_Mod.mSoundNames.add("note.bass");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.glass, 1));
    	GT_Mod.mSoundNames.add("note.hat");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.sand, 1));
    	GT_Mod.mSoundNames.add("note.snare");
    	GT_Mod.mSoundCounts.add(25);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.recordCat, 1));
    	GT_Mod.mSoundNames.add("streaming.");
    	GT_Mod.mSoundCounts.add(12);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.tnt, 1));
    	GT_Mod.mSoundNames.add("random.explode");
    	GT_Mod.mSoundCounts.add(3);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.fire, 1));
    	GT_Mod.mSoundNames.add("fire.fire");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.flintAndSteel, 1));
    	GT_Mod.mSoundNames.add("fire.ignite");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.lavaMoving, 1));
    	GT_Mod.mSoundNames.add("liquid.lavapop");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.waterMoving, 1));
    	GT_Mod.mSoundNames.add("liquid.water");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.bucketWater, 1));
    	GT_Mod.mSoundNames.add("liquid.splash");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.bucketLava, 1));
    	GT_Mod.mSoundNames.add("random.fizz");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.portal, 1));
    	GT_Mod.mSoundNames.add("portal.portal");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.endPortal, 1));
    	GT_Mod.mSoundNames.add("portal.travel");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.endPortalFrame, 1));
    	GT_Mod.mSoundNames.add("portal.trigger");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.thinGlass, 1));
    	GT_Mod.mSoundNames.add("random.glass");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.enderPearl, 1));
    	GT_Mod.mSoundNames.add("random.orb");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.eyeOfEnder, 1));
    	GT_Mod.mSoundNames.add("random.levelup");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.stoneButton, 1));
    	GT_Mod.mSoundNames.add("random.click");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.cobblestone, 1));
    	GT_Mod.mSoundNames.add("damage.fallbig");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.dirt, 1));
    	GT_Mod.mSoundNames.add("damage.fallsmall");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.swordIron, 1));
    	GT_Mod.mSoundNames.add("damage.hurtflesh");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.swordDiamond, 1));
    	GT_Mod.mSoundNames.add("random.hurt");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.bow, 1));
    	GT_Mod.mSoundNames.add("random.bow");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.arrow, 1));
    	GT_Mod.mSoundNames.add("random.drr");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.fishingRod, 1));
    	GT_Mod.mSoundNames.add("random.bowhit");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.shovelIron, 1));
    	GT_Mod.mSoundNames.add("random.break");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.bucketEmpty, 1));
    	GT_Mod.mSoundNames.add("random.breath");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.potion, 1));
    	GT_Mod.mSoundNames.add("random.drink");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.glassBottle, 1));
    	GT_Mod.mSoundNames.add("random.burp");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.enderChest==null?Blocks.obsidian:Blocks.enderChest, 1));
    	GT_Mod.mSoundNames.add("random.chestopen");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.chest, 1));
    	GT_Mod.mSoundNames.add("random.chestclosed");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.doorIron, 1));
    	GT_Mod.mSoundNames.add("random.door_open");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.doorWood, 1));
    	GT_Mod.mSoundNames.add("random.door_close");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Items.porkRaw, 1));
    	GT_Mod.mSoundNames.add("random.eat");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.cloth, 1));
    	GT_Mod.mSoundNames.add("step.cloth");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.grass, 1));
    	GT_Mod.mSoundNames.add("step.grass");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.gravel, 1));
    	GT_Mod.mSoundNames.add("step.gravel");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.snow, 1));
    	GT_Mod.mSoundNames.add("step.snow");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.pistonBase, 1));
    	GT_Mod.mSoundNames.add("tile.piston.out");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.pistonStickyBase, 1));
    	GT_Mod.mSoundNames.add("tile.piston.in");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.cobblestoneMossy, 1));
    	GT_Mod.mSoundNames.add("ambient.cave.cave");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.blockLapis, 1));
    	GT_Mod.mSoundNames.add("ambient.weather.rain");
    	GT_Mod.mSoundCounts.add(1);
    	GT_Mod.mSoundItems.add(new ItemStack(Blocks.blockDiamond, 1));
    	GT_Mod.mSoundNames.add("ambient.weather.thunder");
    	GT_Mod.mSoundCounts.add(1);
	}
}
